### ISSUE TITLE
Nothing happens when aligning

### ISSUE THREAD

**Issue by csrui** [tuvistavie/atom-align-regexp#2]
Maybe its me but when I select some code and then do "Align Selection" nothing happens. The mini editor does not appear for the regex input.

Running Atom 1.8.0

**Comment by danhper** [comment]
Hi, thanks for reporting.
I am also running Atom version 1.8.0 and everything is working fine,
so maybe there is a compatibility issue with some other plugin.
Do you get any error in the developer tools?
Also, be sure to try to restart Atom if you did not already.

**Comment by csrui** [comment]
I have tried restarting and also disabling every other alignment plugin
just in case. No Joy.
I've also tried with a different theme still no joy.
The console shows no errors.

To be honest, I never actually seen what you call of "mini editor" :|

**Comment by danhper** [comment]
Thanks for the extra information.
Did you try to run it from the command palette?
Normally it should look something like this:

![align-regexp](https://cloud.githubusercontent.com/assets/1436271/17239017/bfb466ba-559b-11e6-8086-81ab55c52d06.gif)

If it still does not work, could you try in a clean Atom installation.
It is easy to do if you use the `ATOM_HOME` environment variable, for example
by using something like this:

```
cd $(mktemp -d)
ATOM_HOME=$(pwd) atom
```

Thank you!

**Comment by averyvery** [comment]
Ran into a similar bug after just upgrading atom to 1.13.0 on OSX — running from keyboard or command palette doesn't produce a text area for the character, and there seem to be no console errors. 

I started a fresh Atom installation as per your above instruction, and installed only your addon, and the result seems to be the same.

![no-effect](https://cloud.githubusercontent.com/assets/72114/21860680/f2b61254-d7ee-11e6-9ebb-e0e86f9adc94.gif)

**Comment by danhper** [comment]
This should be fixed in the latest version, please reopen if it still does not workl

**Comment by averyvery** [comment]
Works! Thank you!!!
