### ISSUE TITLE
Repeat regexp or option?

### ISSUE THREAD

**Issue by polarathene** [tuvistavie/atom-align-regexp#3]
Hi there, excellent plugin! Just ran into a situation where aligning via regexp was the solution (`\/>.*<!` for XML right side comments in this case). Problem is I don't see a way that I can repeat the command easily without having to add the extra paste regexp step + enter.

Would it be possible to add a function to use a specific(options) or last regexp used? Using the last regexp might be most useful(and easiest to implement?), but I could imagine some one might have a need for using the pattern again and wanting to store it in a config.

**Comment by danhper** [comment]
Hi, thanks for the idea!

Indeed for a complicated regexp it is a pain to have to copy-paste everytime.

A (possibly persistent) history seems a better solution than storing things in the config for this use case.

We would probably need to do the the following
- Store the regexp in the history when running `align-regexp:align`
- Implement `align-regexp:previous-item` to select the history previous when focusing the align textarea
- Optionally implement `align-regexp:next-item` to be able to select the next item in the history after using `align-regexp:previous-item`.

What do you think? Would that fit your needs?

**Comment by polarathene** [comment]
I've not worked on an atom package before but I'm familiar with ES6. Have been trying to hack in the feature for myself after posting this :) Didn't expect the fast response!

I got it to work by:
- Adding a `prevPattern: null,` property to the `align-regexp.js` class
- In the `executeAlign(regexp)` method I stored the last successful regexp value with `this.prevPattern = regexp;`(I placed this after the try/catch but I'm sure it would work fine prior to reassigning the regexp string to RegExp value?)
- Added a method `alignWithPrevPattern()` that calls `this.executeAlign(this.prevPattern);`
- Subscribed with `align-regexp:align-with-prev-pattern` in `activate(state)` and updated the two json configs for menu's to use it. Assigned the keymap `ctrl-shift-a`, not sure what would be most appropriate.

It may not be the best approach as I'm not familiar with developing Atom packages. Let me know if you'd like a PR :)

---

A persistent history may be useful to others? If I were a regular user of the plugin with several regexp to use, I imagine I'd want to keybind to each one or use a drop-down to select one to use multiple times(In my case I have many elements that need their children aligned, requiring me to do one element at a time, not sure if I could automate this without some regexp select package that can iterate through each element calling align-regexp).

If history is just for the session store it in a set so that the stored expressions have no duplicates? The user could then input/store their regexp patterns in package settings or with the current input have a checkbox to toggle storing. You could then either display the history via drop-down or prev/next buttons(caret arrows).

**Comment by danhper** [comment]
@polarathene Hi, thanks for working on that!
I agree it is quite common to reuse the same regexp multiple times, so I think your approach is quite nice.
I would be very pleased to merge it if you send me a PR.

> If history is just for the session store it in a set so that the stored expressions have no duplicates? The user could then input/store their regexp patterns in package settings or with the current input have a checkbox to toggle storing. You could then either display the history via drop-down or prev/next buttons(caret arrows).

Yeah, this is pretty much what I had in mind, but as I don't really need it this much myself,
let's see if the addition you made is good enough for your needs.

If it still isn't enough, let's discuss further to see what could be improved!

**Comment by polarathene** [comment]
Oh sorry, I was busy and forgot all about this! Glad to see you've added the feature :)

**Comment by danhper** [comment]
No problem, and thanks for the idea :smile: 
I finally implemented it using a permanent history.
