### ISSUE TITLE
With Atom v1.13.0 "Align Section" command no longer does anything at all, pattern-entry field does not appear

### ISSUE THREAD

**Issue by rodw** [tuvistavie/atom-align-regexp#4]
Recently (as of Atom v1.13.0 or maybe the release before this), align-regexp no longer calls up the little mini-editor for entering the pattern to align on, and hence doesn't do anything at all.

It is possible that an updated version of another package is now interfering with align-regexp, but I have not installed any new packages, just upgraded via the squirrel prompt from the status bar.

Let me know if there is something I can do to help troubleshoot.

**Comment by rodw** [comment]
I meant to add that no errors are reported to the Developer Tools JavaScript console.

**Comment by danhper** [comment]
This should now be fixed in the latest version.
Thank you for reporting and sorry for the delay!
